### ISSUE TITLE
Hash Sum mismatch issue caused Unable to fetch some archives

### ISSUE THREAD

**Issue by Tanete** [andreychernih/railsbox#10]
I try to vagrant up with [thif config](https://railsbox.io/boxes/88cded04965a) on my Windows PC.
And run into such kind of problem:

>msg: 'apt-get install 'autoconf' 'bison' 'build-essential' 'libssl-dev' 'libyaml-dev' 'libreadline6-dev' 'zlib1g-dev' 'libncurses5-dev' 'nodejs' 'python-pip' 'python-dev' 'htop' 'git'' failed: E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/a/automake-1.14/automake_1.14.1-2ubuntu1_all.deb  Hash Sum mismatch

Is this due to my network issue? I tried this in my school serveral times and failed.

This is my [console log](https://gist.github.com/Tanete/6cbae60364ba815aabac).

**Comment by andreychernih** [comment]
I guess such things can happen because of network glitches. Also try to disable firewall (if you have one). Since some of packages were downloaded successfully (as I see in your console log), I would try to run the following:

 ```
sudo rm -rf /var/lib/apt/lists/*
sudo apt-get update
```

And then re-run `vagrant provision`.

**Comment by Tanete** [comment]
Yeah. I changed the sources.list mirror and tried again. It worked.
