### ISSUE TITLE
Install ruby with rvm (--binary flag)

### ISSUE THREAD

**Issue by d0m0v0y** [andreychernih/railsbox#13]
If rvm doesn't have the binary package for selected version of ruby, vagrant provision failed with error.

```
stderr: Requested binary installation but no rubies are available to download, consider skipping --binary flag.
stdout: Searching for binary rubies, this might take some time.
```

**Comment by RDrop** [comment]
I got the same problem.

A solution for now is to set the Ruby version to 2.1.5

**Comment by d0m0v0y** [comment]
Or remove --binary flag here: https://github.com/andreychernih/railsbox/blob/master/templates/ansible/roles/ruby/tasks/rvm.yml#L60

**Comment by RDrop** [comment]
I forked this project and updated it with removed binary flag (2.2.0 installs without error)
Added a apt-get update
Added the option to use nginx + puma.
Upgraded the postgresql version to 9.4
Changed the nodejs to download the lastest version, and install
Added the option to include a sidekiq.rb config file that connects to activerecord and redis.rb if they are chosen

I'm going to submit a pull request and in the mean time you can access it here: https://github.com/RDrop/railsbox

**Comment by RDrop** [comment]
submitted a pull request
