### ISSUE TITLE
Nginx / Unicorn error when trying to access the app

### ISSUE THREAD

**Issue by kitsched** [andreychernih/railsbox#17]
I created [this box](https://railsbox.io/boxes/c75534defd2f) and provisioning went well. However when I'm trying to access the app via `http://localhost:8080` I get the following in the nginx error.log:

    2015/03/22 22:27:02 [crit] 1134#0: *1 connect() to unix:/tmp/unicorn.development.sock failed (2: No such file or directory) while connecting to upstream, client: 10.0.2.2, server: localhost, request: "GET / HTTP/1.1", upstream: "http://unix:/tmp/unicorn.development.sock:/", host: "localhost:8080"

I [read](http://serverfault.com/a/464025) that this might be because it is not possible to store the socket files in /tmp anymore, but I'm not sure if this applies to Ubuntu.

**Comment by andreychernih** [comment]
I've just tried to use your railsbox in [testapp1](https://github.com/andreychernih/railsbox/tree/master/spec/fixtures/testapp1) and it worked. I would suggest to ssh into the box (`vagrant ssh`) and see if unicorn is actually running. If it's not running then try to take a look at `/rcheliwiki/log/unicorn.err.log`.
