### ISSUE TITLE
rvm 

### ISSUE THREAD

**Issue by jcward10** [andreychernih/railsbox#20]
When running the production play book, I received an error `cannot mkdir /home/deploy/.rvm`. 
I was able to ssh into my VPS and manually make the directory. I was wondering if you could give me some guidance here. I am new to ansible and I didn't find too much documentation about production deployment for railsbox.

**Comment by jcward10** [comment]
So I was able to get past making the need directories by manually going into my VPS. Then, received this error message. `stderr: Requested binary installation but no rubies are available to download, consider skipping --binary flag.
stdout: Searching for binary rubies, this might take some time.
...ignoring`

Followed by freezing on `TASK: [ruby | Install rubies (non-binary)] ************************`

**Comment by andreychernih** [comment]
Looks like it can't find binaries for the version you've selected and it's normal, this error is being ignored by ansible. It then tries to install non-binary version which can take a while because it compiles ruby from source.
