### ISSUE TITLE
Ansible doesn't pick up variables in other directories in group_vars

### ISSUE THREAD

**Issue by fonglh** [andreychernih/railsbox#23]
I only have a staging environment configured. The variables in `group_vars/staging/config.yml` are not picked up.

Do they have to be manually included somewhere?

**Comment by BrVer** [comment]
i have the same issue, maybe i'm doing something wrong? 
https://railsbox.io/boxes/ac1ccd5f73ff, after unzipping it to project directory and installing ansible, I perform:
cd railsbox/staging
sh provision.sh
and it seems like ansible do not see group_vars/staging/config.yml variables 
@fonglh, maybe you have a solution?

**Comment by jtomaszewski** [comment]
> UPD: seems like it's caused by staging/inventory having [development] section instead of [staging]

Fixed it to me. Thanks @BrVer

**Comment by andreychernih** [comment]
This should be fixed now, thanks to @kraft001
