### ISSUE TITLE
Puma not creating PID or Socket

### ISSUE THREAD

**Issue by techdaddies-kevin** [andreychernih/railsbox#25]
Configuration at https://railsbox.io/boxes/0e2a475a6b52

Running this on an Ubuntu 12 host. 

When the box boots, everything starts up but puma doesn't actually create the socket file or the pid file. The vagrant user has permissions on the tmp directory so I'm not sure what's going on. Nothing crazy showing up in syslog either.

Any ideas? I'm not sure where else to investigate at this point.

**Comment by andreychernih** [comment]
Closed by https://github.com/andreychernih/railsbox/pull/33

**Comment by arifb** [comment]
I'm not sure this is fixed by #33 @andreychernih? The pid and sockets base directory is /tmp is which is wiped on every restart of Ubuntu. So unless you provision every startup, puma is not going to be able to create the pid or sockets files. At least that's what I'm seeing.

**Comment by kraft001** [comment]
You're right, there's a problem with the `/tmp` folder.
As for me, I added a couple lines of code to the upstart script to create those folders, but haven't got enough time to make a PR. So, no need to provision every startup )

**Comment by arifb** [comment]
Thanks @kraft001 - I'm happy to provide a PR. My thinking is we keep these files out /tmp and maybe something like /var/tmp/{project}/sockets/ etc.?
