### ISSUE TITLE
Error in TASK: [postgresql | Create config/database.yml] ***************************

### ISSUE THREAD

**Issue by bunset** [andreychernih/railsbox#32]
Hello,
I get errors in my vagrant up step:
These are the errors. Maybe you know how to fix them. Thank you and kind regards:

TASK: [postgresql | Create config/database.yml] ******************************* 
failed: [myapp] => {"failed": true}
msg: Destination directory /myapp/config does not exist

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/Users/David/site.retry

myapp                      : ok=13   changed=1    unreachable=0    failed=1   

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.

**Comment by chalkos** [comment]
I also have this error

**Comment by chalkos** [comment]
@bunset create a rails project before running `vagrant up`, then it will work

**Comment by andreychernih** [comment]
Closed by https://github.com/andreychernih/railsbox/pull/33
