### ISSUE TITLE
Sidekiq fails to include Redis

### ISSUE THREAD

**Issue by iamkobold** [andreychernih/railsbox#39]
When selecting SideKiq it should probably also include installing redis as well since that's the default. After a while I realized there is an option to install redis as an ORM however i wasn't aware of that option so I guess the real issue here is to make redis automatic with sidekiq if it isn't already available in the instance somewhere.

**Comment by andreychernih** [comment]
Thanks for the report. This is not supported at the moment indeed. I would consider this as a new feature. Unfortunately, I don't have any bandwidth right now to implement it. Feel free to submit PR if you really want this to be included.
