### ISSUE TITLE
Underscore in Application Name field produces error

### ISSUE THREAD

**Issue by cdesch** [andreychernih/railsbox#6]
Putting a underscore in the application name field and creating the box produces a application error.

![screen shot 2015-01-18 at 1 39 02 pm](https://cloud.githubusercontent.com/assets/1207795/5793577/960762ae-9f17-11e4-8ddb-5bd1e4c4c8d8.png)

Error:

![screen shot 2015-01-18 at 1 39 10 pm](https://cloud.githubusercontent.com/assets/1207795/5793578/9bb2417e-9f17-11e4-8199-f360ae4bab30.png)

Everything else works fine if the underscore is removed.

**Comment by andreychernih** [comment]
Should be fine now.
