### ISSUE TITLE
redis-server

### ISSUE THREAD

**Issue by EdgarOrtegaRamirez** [andreychernih/railsbox#7]
I had to manually install `redis-server` after `vagrant up`.

`$ sudo apt-get install redis-server`

**Comment by andreychernih** [comment]
That's really strange. I know, it's a stupid question, but have you actually added redis in Databases section? Also, if you can share box URL, it would be helpful.

**Comment by EdgarOrtegaRamirez** [comment]
I just found out that Redis is a dependency in my project, and this is not an issue but a feature request to add `redis-server` to the Additional packages section.

**Comment by andreychernih** [comment]
You can add redis in Databases section and it will install `redis-server`.
